let cart=JSON.parse(localStorage.getItem('cbcart')||'[]'),orders=JSON.parse(localStorage.getItem('cborders')||'[]');
const money=n=>'G '+Number(n).toLocaleString('en-US',{minimumFractionDigits:2});
function save(){localStorage.setItem('cbcart',JSON.stringify(cart));localStorage.setItem('cborders',JSON.stringify(orders))}
function add(name,price){cart.push({name,price});save();renderCart();cartOpen()}
function renderCart(){document.getElementById('badge').textContent=cart.length;let t=cart.reduce((s,x)=>s+x.price,0);document.getElementById('total').textContent=money(t);document.getElementById('cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="row"><span>${x.name}</span><b>${x.price?money(x.price):'Sur demande'} <button onclick="removeItem(${i})">×</button></b></div>`).join(''):'<p style="text-align:center;color:#999;margin-top:70px">Votre panier est vide.</p>'}
function removeItem(i){cart.splice(i,1);save();renderCart()}
function cartOpen(){document.getElementById('drawer').classList.add('open');document.getElementById('backdrop').classList.add('show');renderCart()}
function cartClose(){document.getElementById('drawer').classList.remove('open');document.getElementById('backdrop').classList.remove('show')}
function page(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo(0,0);if(id==='orders')renderOrders()}
function menu(){alert('Menu : Accueil · Services · Portefeuille · Commandes · Support')}
function checkout(){if(!cart.length)return alert('Votre panier est vide.');cartClose();document.getElementById('checkItems').innerHTML=cart.map(x=>`<div class="row"><span>${x.name} × 1</span><b>${x.price?money(x.price):'Sur demande'}</b></div>`).join('');document.getElementById('checkTotal').textContent=money(cart.reduce((s,x)=>s+x.price,0));document.getElementById('modal').classList.add('show')}
function closeCheckout(){document.getElementById('modal').classList.remove('show')}
function order(){if(!ln.value||!fn.value||!wa.value||!mail.value)return status.textContent='Veuillez remplir les champs obligatoires.';if(!terms.checked)return status.textContent='Veuillez accepter les conditions générales.';let id=Math.floor(10000+Math.random()*89999);orders.unshift({id,items:[...cart],date:new Date().toLocaleDateString('fr-FR'),total:cart.reduce((s,x)=>s+x.price,0)});cart=[];save();renderCart();status.textContent='Commande #'+id+' créée avec succès.';setTimeout(()=>{closeCheckout();page('orders')},900)}
function renderOrders(){ordersList.innerHTML=orders.length?orders.map(o=>`<div class="panel"><div class="total"><b>Commande #${o.id}</b><b>${o.total?money(o.total):'Sur demande'}</b></div><p style="font-size:12px;color:#888">${o.items.map(x=>x.name).join(' · ')}</p><small>${o.date} · En attente</small></div>`).join(''):'<div class="panel" style="text-align:center;color:#999;padding:60px">Aucune commande récente.</div>'}
function funds(){let n=Number(amt.value);if(n>0){let v=Number(walBal.textContent)+n;walBal.textContent=v.toFixed(2);headBal.textContent=v.toFixed(2);amt.value=''}}
renderCart();